### ISSUE TITLE
WR2: Bem 2.2.2, Def. 2.2.6

### ISSUE THREAD

**Issue by daavu** [ChrisTX/lecture-notes#2]
Bei der Spur \gamma_0 sollte etwas wie meas(...) als Vorfaktor stehen und im Integrationsgebiet fehlt \Omega.

Die Definition von H^\frac{1}{2} (\partial\Omega) ist auch etwas merkwürdig. War wohl sicher Im(\Gamma_0) gemeint.

Definition 2.2.6. Der zweite Term mit dem \beta muss noch mit v multipliziert werden.

**Comment by ChrisTX** [comment]
Danke, bei \gamma_0 glaube ich dass das fehlende meas(...) schon in der Vorlesung so war.

Die Definition von H^\frac{1}{2} ist aber richtig. \gamma_0 ist punktweise auf dem ganzen Rand definiert, weil das eben als Spuroperator genau so gedacht ist.
