### ISSUE TITLE
Kasten erscheint in Prop 1.19

### ISSUE THREAD

**Issue by Mallocsizeofint** [ChrisTX/lecture-notes#4]
![extrakasten](https://cloud.githubusercontent.com/assets/5853425/7357939/62d5d212-ed32-11e4-9bc3-dc82b54a7075.png)

**Comment by Mallocsizeofint** [comment]
Ah, sehe gerade, dass der nicht einfach random überflüssig ist, sondern wohl um das Problem gehört. Damit ist die Problembeschreibung dann eher "Kasten ist zu weit oben".

**Comment by ChrisTX** [comment]
Ich hab keinen DVI viewer installiert (in der PDF ist der Frame richtig gesetzt), deswegen kann ich das jetzt nicht reproduzieren.

Eigentlich soll der Kasten nur die Problemstellung einrahmen, ja.

**Comment by ChrisTX** [comment]
Hab mir das "Problem" mal angeguckt; das liegt dran, dass die Frames per pgf-tikz gezeichnet werden. Zusätzlich kann auch hyperref ein Problem sein.

Mit dvips als Renderer würde das sowieso gehen, aber ich habe mal mittels \ifpdf im Falle von nicht-PDF Ausgabe hypertex als backend driver für Hyperref und default framing für mdframed eingestellt.
